package sessionswitcher.settings

import sessionswitcher.ui.misc.*
import javax.swing.*

class SettingsWindow(val settings: Settings) : Window("InQL Settings") {
    class CheckBoxElement(val item: BooleanSetting): CheckBox(item.description, item.get(SettingsItem.Scope.EFFECTIVE_GLOBAL)) {
        init {
            this.addItemListener {
                item.set(this.isSelected(), SettingsItem.Store.GLOBAL)
            }
        }
    }

    class SpinnerElement(val item: IntSetting, min: Int, max: Int): Spinner(item.description, min, max) {
        init {
            this.setValue(item.get(SettingsItem.Scope.EFFECTIVE_GLOBAL))
            this.addChangeListener {
                item.set(this.getValue(), SettingsItem.Store.GLOBAL)
            }
        }
    }

    class ComboBoxElement(val item: StringSetting, vararg items: String): ComboBox(item.description, *items) {
        init {
            this.setSelectedItem(item.get(SettingsItem.Scope.EFFECTIVE_GLOBAL))
            this.addItemListener {
                item.set(this.getSelectedItem(), SettingsItem.Store.GLOBAL)
            }
        }
    }

    class TextFieldElement(val item: StringSetting, columns: Int = 20): TextField(item.description, columns) {
        init {
            this.setText(item.get(SettingsItem.Scope.EFFECTIVE_GLOBAL))
            this.changeListener = fun() {
                item.set(this.getText(), SettingsItem.Store.GLOBAL)
            }
        }
    }

    class TextAreaElement(val item: StringSetting, rows: Int, columns: Int): TextArea(item.description, rows, columns) {
        init {
            this.setText(item.get(SettingsItem.Scope.EFFECTIVE_GLOBAL))
            this.changeListener = fun() {
                item.set(this.getText(), SettingsItem.Store.GLOBAL)
            }
        }
    }

    class SettingsSection(val sectionTitle: String, val description: String, vararg elements: JComponent?) :
        BorderPanel(10) {
        init {
            val innerBox = BoxPanel(BoxLayout.Y_AXIS, gap = 0)

            for (e in elements) {
                if (e != null) {
                    innerBox.add(e)
                } else {
                    innerBox.add(Box.createVerticalStrut(10))
                }
            }
            val padded = BorderPanel(0, 10)
            padded.add(innerBox)

            val outerBox = BoxPanel(
                BoxLayout.Y_AXIS,
                gap = 10,
                BorderPanel(0).also { it.add(Label(sectionTitle, big = true)) },
                BorderPanel(0).also { it.add(Label(description)) },
                padded,
            )

            this.add(outerBox)
        }
    }

    init {
        // Build the different section first
        val codeGenerationSection = SettingsSection(
            "Code generation settings",
            "Use these settings to configure how the code generated by InQL will look like.",
        )

        val reportSection = SettingsSection(
            "Additional GraphQL reports",
            "Use these settings to configure additional reports generated by InQL.",

        )

        val featuresSection = SettingsSection(
            "InQL Features",
            "Select which features to enable. Reloading the extension or restarting Burp may be required to apply the changes.",

        )

        val integrationsSection = SettingsSection(
            "InQL Integrations",
            "Configure integrations with embedded tools.",
        )

        val poiSection = SettingsSection(
            "Points of interest",
            "Use these settings to configure how InQL will handle points of interest.",
          )

        val loggingLevelSection = SettingsSection(
            "Logging options",
            "Use these settings to configure the logging level of the extension.",
            ComboBoxElement(
                settings.loggingLevel,
                "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL",
            ),
        )

        // Build the main window
        val boxed = BoxPanel(
            BoxLayout.Y_AXIS,
            gap = 0,
            codeGenerationSection,
            JSeparator(JSeparator.HORIZONTAL),
            featuresSection,
            JSeparator(JSeparator.HORIZONTAL),
            integrationsSection,
            JSeparator(JSeparator.HORIZONTAL),
            reportSection,
            JSeparator(JSeparator.HORIZONTAL),
            poiSection,
            JSeparator(JSeparator.HORIZONTAL),
            loggingLevelSection,
            JSeparator(JSeparator.HORIZONTAL),
        )
        val padded = BorderPanel(0, 20).also { it.add(boxed) }
        val scrollable = JScrollPane(padded)
        scrollable.verticalScrollBarPolicy = JScrollPane.VERTICAL_SCROLLBAR_ALWAYS
        scrollable.horizontalScrollBarPolicy = JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED

        this.add(scrollable)

        this.autoSize()
    }
}
